server:
  port: 9091
  #服务应用端口


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka
      # 向注册中心申请

  #默认注册时使用的是主机名或者localhost，如果想用ip进行注册，可以添加配置如下
  instance:
    ip-address: 127.0.0.1 #ip地址
    prefer-ip-address: true #更倾向于使用ip，而不是host名
    lease-expiration-duration-in-seconds: 90 #服务续约(renew)的间隔，默认为30秒
    lease-renewal-interval-in-seconds: 30 #服务失效时间，默认值90秒
    #默认情况下每隔30秒服务会向注册中心发送一次心跳，证明自己还活着。如果超过90秒没有发送心跳，
    #EurekaServer就会认为该服务宕机，会定时（eureka.server.eviction-interval-timer-in-ms设定的时间）从服务列表
    #中移除，这两个值在生产环境不要修改，默认即可。
#日志
logging:
  level:
    com.sky: info
  path: E:\\log

#feign管理的项目开启熔断器
feign:
  hystrix:
    enabled: true